#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'chef-client'

cookbook "wordpress-nginx",
  :git => "https://github.com/roots/wordpress-nginx.git",
  :ref => "master"

cookbook "grunt_cookbook",
  :git => "https://github.com/MattSurabian/grunt_cookbook.git",
  :ref => "master"

cookbook "wp-cookbook",
  :git => "https://github.com/roots/wp-cookbook.git",
  :ref => "master"