#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'chef-client'

cookbook 'ohai'
cookbook 'yum'
cookbook 'apt'

# Packages for installing C from source
cookbook 'build-essential', '1.4.2'

# Database
cookbook 'database', '1.6.0'
cookbook 'mysql', '4.0.14'

# Misc
cookbook 'composer', '0.0.6'
cookbook 'git', '2.9.0'
cookbook 'screen'

# Editors
cookbook 'vim'
cookbook 'nano'

# Web
cookbook 'nginx', '1.7'
cookbook 'php', '1.3.0'             # Note: Versions from 1.3.1 - 1.3.10 seem to fail (tested on CentOS 6.4/6.5)
cookbook 'phpunit', '>= 0.0.9'
cookbook 'php-fpm', '0.6.3'

cookbook "wordpress-nginx",
  :git => "https://github.com/roots/wordpress-nginx.git",
  :ref => "master"

cookbook "grunt_cookbook",
  :git => "https://github.com/MattSurabian/grunt_cookbook.git",
  :ref => "master"

cookbook "wp-cookbook",
  :git => "https://github.com/roots/wp-cookbook.git",
  :ref => "master"